---
title: Elias Meire
timezone: UTC
collections:
  favicon:
    title: Favicon
    output: true
    permalink: "/"
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
incremental: true
description: Personal website of Elias Meire
author: Elias Meire
email: me@eliasmei.re
github_username: eliasmeire
primary_color: "#212121"
compress_html:
  comments: all
  clippings: all
exclude:
- README.md
- package.json
- gulpfile.js
- build.sh
- node_modules/
